// Code generated by github.com/izumin5210/gex. DO NOT EDIT.

// +build tools

package tools

// tool dependencies
import (
	_ "github.com/envoyproxy/protoc-gen-validate"
	_ "github.com/frapposelli/wwhrd"
	_ "github.com/gogo/protobuf/protoc-gen-gogofast"
	_ "github.com/uber/prototool/cmd/prototool"
	_ "go.zenithar.org/protoc-gen-cobra"
	_ "gotest.tools/gotestsum"
	_ "mvdan.cc/gofumpt"
)
